### ISSUE TITLE
[Feature Request] Deal with Message requests bloating the file

### ISSUE THREAD

**Issue by sy-python** [lensvol/fl-request-sounder#1]
**Type:** Feature Request
**Title:** Deal with Message requests bloating the file
**Explanation:** Message requests happen regularly and take up a huge amount of space, making parsing the log file less memory and time efficient. Perhaps an option to turn off tracking these requests?

**Comment by lensvol** [comment]
While I am reluctant to exclude `/messages` from tracking completely, one of the workarounds may be to treat it differently from other requests. For example, check the response for that API call and only record it if the contents differ from the ones seen before that moment.

**Comment by sy-python** [comment]
That would work

**Comment by sy-python** [comment]
Appears to be solved in bc57a89d3bf406080591e046a4ee668bbce343ab

**Comment by lensvol** [comment]
Yes, forgot to mark it as such. :) Will make a new release in the evening.
