### ISSUE TITLE
QoL: Confirm navigating away from a running recording

### ISSUE THREAD

**Issue by kkotenko** [lensvol/fl-request-sounder#3]
As a user who is running a recording, I don't want to close the tab where the recording is running without saving the recording or a confirmation, because I don't want to lose the recorded data.

Suggestion: define an `onbeforeunload` event that will be triggered if the user closes the page while recording is in progress. Not sure how easy it is to determine the latter and what the event needs to be bound to (it's late here).

**Comment by lensvol** [comment]
Good idea, implemented in c53478ba02a518c1398fcb4bf2cf527b58c8def6. Thank you!
